config/routes.rb
HackDay::Application.routes.draw do
  
  #get "conferencias/index"
  get "conferencias/ponencias"
  get "conferencias/talleres"
  get "conferencias/costos"
  get "reportes/index"
  get "reportes/correos"  
  get "cronogramas/index"
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :personas
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/estudio.rb
class Estudio < ActiveRecord::Base
	has_many :personas
	
	validates_uniqueness_of :nombre
	validates_presence_of :nombre
end

app/models/evento.rb
class Evento < ActiveRecord::Base
	has_many :personas_eventos
	has_many :personas, :through => :personas_eventos
end

app/models/institucion.rb
class Institucion < ActiveRecord::Base
	#has_many :personas
	
	validates_uniqueness_of :nombre
	validates_presence_of :nombre
end

app/models/persona.rb
class Persona < ActiveRecord::Base
	belongs_to :region
	#belongs_to :institucion
	belongs_to :estudio
	
	has_many :personas_eventos
	has_many :eventos, :through => :personas_eventos
		
	validates :nombres, :apellidos, :email, :estudio_id, :presence => true
	
	#validates_uniqueness_of :dni
	validates_uniqueness_of :email
	#validates :dni,length: { is: 8}, :presence => true
	#validates_format_of :dni, :with => /\A[0-9]{8}\Z/
	
	validates_uniqueness_of :celular
	validates :celular,length: { is: 9}, :presence => true
	validates_format_of :celular, :with => /\A[0-9]{9}\Z/
	
	validates :comentario, length: { maximum: 150}
	
	validates :conferencia, :presence => true 
	validates :conferencia, length: { maximum: 40}
	before_validation( :on => :create) do
		predeterminados
	end	
	
	def predeterminados
		self.institucion = 'No se indico' if self.institucion.blank?		
		self.comentario = 'No comento' if self.comentario.blank?
	end
end

app/models/personas_eventos.rb
class PersonasEventos < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :personas
	
	validates_uniqueness_of :nombre
	validates_presence_of :nombre
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  # :registerable,	sirve para crear nuevos usuarios
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable,:timeoutable
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
  redirect_to root_path, :alert => exception.message
  end

end

app/controllers/conferencias_controller.rb
class ConferenciasController < ApplicationController
  def index
  end

  def ponencias
  end

  def talleres
  end

  def costos
  end
end

app/controllers/cronogramas_controller.rb
class CronogramasController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
  before_action :set_persona, only: [:show, :edit, :update, :destroy]
  
  def edit
  end

  def new
	@persona = Persona.new
  end

  def create
	@persona = Persona.new(persona_params)
	
	if @persona.save
		flash[:notice]="Se registró correctamente"
		redirect_to root_path
	else
		render action: 'new'
	end
  end
  
  def show
  end
  
  def update
	if @persona.update(persona_params)
		flash[:notice]="Se actualizó los datos"
		redirect_to @persona
     else
        render action: 'edit'        
     end
  end
  def confirmar
  end
  def destroy
    @persona.destroy
    redirect_to reportes_index_path
  end
  private
  
  def set_persona
	@persona = Persona.find(params[:id])
  end
  
  def persona_params
	params.require(:persona).permit(:dni, :nombres, :apellidos, :email, :celular, :institucion, :region_id, :comentario, :estudio_id,:conferencia)
  end  
end

app/controllers/reportes_controller.rb
class ReportesController < ApplicationController
  before_filter :authenticate_user!
  
  def index
	@personas=Persona.all
	@totalpersona=Persona.count
  end
  
  def correos
	@personas=Persona.all.order("region_id")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/conferencias_helper.rb
module ConferenciasHelper
end

app/helpers/cronogramas_helper.rb
module CronogramasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/reportes_helper.rb
module ReportesHelper
end

app/views/conferencias/_costo.html.erb
<div class="text-center">
	<p>_________________________________________________________</p>
	<p><%= link_to image_tag("inversion.png"), root_path %></li></p>
	<p>_________________________________________________________</p>
</div>
<div class="row-fluid">		
	<div class="span6">			
		<div class="text-success">
			<h2>INVERSIÓN PONENCIA </h2>
			<h3>(Por 2 ponencias)</h3>
			<table class="table ">
				<thead>
					<tr>
						<th>Estudio</th>
						<th>Tarifa</th>
				</tr>
				</thead>
				<tbody>
					<tr>
						<td>Profesional</td>
						<td>S/. 80.00</td>
					</tr>
					<tr>
						<td>Estudiante pre-grado</td>
						<td>S/. 60.00</td>
					</tr>
				</tbody>
			</table>
			<h4>Incluye Certificado</h4>								
		</div>
	</div>		
	<div class="span6">			
		<div class="text-success">
			<h2>INVERSIÓN TALLER</h2>
			<h3>(Por 1 taller)</h3>
			<table class="table ">
				<thead>
					<tr>
						<th>Estudio</th>
						<th>Tarifa</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Profesional</td>
						<td>S/.120.00</td>
					</tr>
					<tr>
						<td>Estudiante pre-grado</td>
						<td>S/. 80.00</td>
					</tr>
				</tbody>
			</table>
			<h4>Incluye Certificado</h4>								
		</div>
	</div>
</div>
<div class="row-fluid">
	<div class="span4">
		<h2>INFORMES</h2>
		<h4 text="text-warning">Descargue aquí más información acerca del evento y los costos</h4>
		<%= link_to image_tag("cloud.png"),"http://www.mediafire.com/folder/lafrqdh45m542/Hackday"%>		
	</div>
	<div class="span2"><%= image_tag("oferta.png")%></div>
	<div class="span6">
		<div class="text-success">
			<h2>INVERSIÓN TALLER</h2>
			<h3>(Por 2 talleres)</h3>
			<table class="table ">
				<thead>
					<tr>
						<th>Estudio</th>
						<th>Tarifa	</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Profesional</td>
						<td>S/.200.00</td>
					</tr>
					<tr>
						<td>Estudiante pre-grado</td>
						<td>S/.140.00</td>
					</tr>
				</tbody>
			</table>
			<h4>Incluye Certificado</h4>								
		</div>
	</div>
</div>	

app/views/conferencias/_descargar.html.erb
<h4 text="text-warning">Descargue aquí más información acerca del evento y los costos</h4>
<%= link_to image_tag("cloud.png"),"http://www.mediafire.com/folder/lafrqdh45m542/Hackday"%>

app/views/conferencias/_ponencia.html.erb
<h1 class="text-info">Ponencias</h1>
<div class="row-fluid">				
	<div class="span6">
		<div class="thumbnails"><%= link_to image_tag("logo.png"), root_path %></div>
	</div>
	<div title="" data-original-title="" class="span6">
		<div class="lugar">
			<h2>Lugar del encuentro</h2>
			<p>Auditorio de la escuela de Ingeniería en Industrias Alimentarias</p>
			<p><i class="icon-map-marker icon-white"></i>Universidad Nacional Jorge Basadre Grohmann</p>
			<h2>Fecha</h2>
			<h4 class="text-center">07 y 08 septiembre</h4>	
			<h2>Horas</h2>
			<h4 class="text-center">De 09:30 a 13:00</h4>									
		</div>            
	</div>				  
</div>
<div class="row-fluid">
	<div class="span6">
		<h3 class="text-info">La actualidad de la seguridad Informática en el Perú</h3>
		<ul class="text-muted">
			<li>Introducción.</li>
			<li>Ataque a las instituciones peruanas.</li>
			<li>¿Quiénes son los Hackers?.</li>
			<li>Hacktivismo en el Perú: Anonymous y LulzSec.</li>
			<li>La internet en el Perú.</li>
			<li>Legislación peruana sobre el hacktivismo: Ley 29733 y ley Beingolea.</li>
			<li>Benchmarking de la seguridad informática en el Perú y latinoamerica.</li>
			<li>Conclusiones.</li>
		</ul>
	</div>
	<div class="span6">
		<h3 class="text-info">Nuevas tendencias en el mundo del Hacking</h3></br>
		<ul class="text-muted">
			<li>Introducción a las nuevas tendencias.</li>					
			<li>Importancia de la ingeniería social.</li>
			<li>Android Mobile Hacking.</li>
			<li>La inseguridad de redes Wireless</li>
			<li>Las apliciones web y sus nuevos mecanismos de seguridad.</li>
			<li>¿Qué nos espera en el futuro?.</li>
			<li>Conclusiones.</li>
		</ul>
	</div>
</div>

	

app/views/conferencias/_taller.html.erb
<h1 class="text-info">Talleres</h1>
<div class="row-fluid">				
	<div title="" data-original-title="" class="span6">
		<div class="lugar">
			<h2>Lugar del encuentro</h2>
			<p>Laboratorio de la escuela de Ingeniería de Informática y Sistemas</p>
			<p><i class="icon-map-marker icon-white"></i>Universidad Nacional Jorge Basadre Grohmann</p>
			<h2>Fecha</h2>
			<h4 class="text-center">07 y 08 septiembre</h4>	
			<h2>Horas</h2>
			<h4 class="text-center">De 15:00 a 20:00</h4>									
		</div>            
	</div>
	<div class="span6">					
		<div class="text-center"><%= link_to image_tag("cad.png"), root_path %></div>					
	</div>						  
</div>
<div class="row-fluid">				
	<div class="span6">
		<h3 class="text-info">Taller de Ethical Hacking y Pentesting</h3>
		<ul class="">				
			<li>Introducción y Metodologías de Ethical Hacking:
				<P class="subtexto"><i class="icon-book icon-white"></i> OSSTMM.</P>
				<p class="subtexto"><i class="icon-book icon-white"></i> ISSAF.</p>
				<P class="subtexto"><i class="icon-book icon-white"></i> Ataque de negación de servicio (DOS).</P>
			</li>				
			<li>Identificación de objetivos de ataque:
				<p class="subtexto"><i class="icon-book icon-white"></i> Footprinting e identificadores de la organización.</p>
				<p class="subtexto"><i class="icon-book icon-white"></i> Scannig de servidores.</p>
				<p class="subtexto"><i class="icon-book icon-white"></i> Enumeración de puertos y servicios.</p>
			</li>
			<li>Análisis de Vunerabilidades
				<p class="subtexto"><i class="icon-book icon-white"></i> Descubrimiento de vunerabilidades en sistemas operativos y apliciones web</p>
			</li>
			<li>Penetración Testing
				<p class="subtexto"><i class="icon-book icon-white"></i> Explotación de vunerabilidades identificadas en sistemas operativos y apliciones web</p>
			</li>
			<li>Introducción a la seguridad de apliciones Web
				<p class="subtexto"><i class="icon-book icon-white"></i> Explotación de vunerabilidades identificadas</p>
			</li>
		</ul>
	</div>
	<div class="span6">
		<h3 class="text-info">Taller de Ethical Hacking en Aplicaciones Web</h3>
		<ul class="">
			<li>Introducción.</li>
			<li>Análisis de las metodologias de seguridad informáticas y diversos tipos de ataque:
				<p class="subtexto"><i class="icon-book icon-white"></i> OWASP</p>
				<p class="subtexto"><i class="icon-book icon-white"></i> Defacements</p>
			</li>
			<li>Identificación de los objetivos de ataque:
				<p class="subtexto"><i class="icon-book icon-white"></i> Footprinting e identificación de la organización</p>
				<p class="subtexto"><i class="icon-book icon-white"></i> Scannig de servidores</p>
				<p class="subtexto"><i class="icon-book icon-white"></i> Enumeración de puertos y servicios</p>
			</li>
			<li>Análisis de Vunerabilidades:
				<p class="subtexto"><i class="icon-book icon-white"></i> Descubrimiento de vunerabilidades en Apliciones Web</p>
			</li>
			<li>Penetration Testing:
				<p class="subtexto"><i class="icon-book icon-white"></i> Inyecciones SQL básicas</p>
				<p class="subtexto"><i class="icon-book icon-white"></i> Inyecciones SQL Avanzadas</p>
				<p class="subtexto"><i class="icon-book icon-white"></i> Upload de archivos maliciosos</p>
				<p class="subtexto"><i class="icon-book icon-white"></i> XSS</p>
				<p class="subtexto"><i class="icon-book icon-white"></i> Inyecciones de código</p>
				<p class="subtexto"><i class="icon-book icon-white"></i> RFI</p>
				<p class="subtexto"><i class="icon-book icon-white"></i> LFI</p>
			</li>
			<li>Técnicas de remediación, prevención.</li>				
		</ul>
	</div>
</div>

app/views/conferencias/costos.html.erb
<div class="hero-unit">
	<%= render "costo"%>
	<%= render "home/informe"%>
</div>

app/views/conferencias/index.html.erb
<div class="hero-unit">
	<%= render "ponencia"%>
	<%= render "taller"%>
	<%= render "home/informe"%>
	<div class="text-center"><%= render "descargar"%></div>
</div>

app/views/conferencias/ponencias.html.erb
<div class="hero-unit">
	<%= render "ponencia"%>
	<%= render "home/informe"%>
	<div class="text-center"><%= render "descargar"%></div>
</div>

app/views/conferencias/talleres.html.erb
<div class="hero-unit">
	<%= render "taller"%>
	<br>
	<div class="nota">NOTA: SI DESEA PARTICIPAR EN TALLERES RESERVE SU ASISTENCIA LO MAS ANTES POSIBLE, CAPACIDAD LIMITADA DE 25 PERSONAS</div>
	<br>
	<%= render "home/informe"%>
	<div class="text-center"><%= render "descargar"%></div>	
</div>

app/views/cronogramas/index.html.erb
<div class="hero-unit">
	<h1 class="text-info">CRONOGRAMA HACKDAY</h1>
	<h2>SÁBADO 07 de Setiembre, 2013</h2>
	<p class>Agregar texto para indicar algunas notas</p>
	<table class="table">
		<thead>
			<tr>
				<th>Hora</th>
				<th>Temas</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>10:00 - 11:00</td>
				<td>Mencionar actividades programadas</td>							
			</tr>
			<tr>
				<td>11:00 - 12:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>12:00 - 01:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>01:00 - 02:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>02:00 - 03:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>03:00 - 04:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>04:00 - 05:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>05:00 - 06:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>06:00 - 07:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>07:00 - 08:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>			
		</tbody>
	</table>
	<h2>Domingo, 08 de Setiembre, 2013</h2>
	<p class>Agregar texto para indicar algunas notas</p>
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Hora</th>
				<th>Temas</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>08:00 - 09:00</td>
				<td>Mencionar actividades programadas</td>							
			</tr>
			<tr>
				<td>09:00 - 10:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>10:00 - 11:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>11:00 - 12:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>12:00 - 01:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>01:00 - 02:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>02:00 - 03:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>03:00 - 04:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>04:00 - 05:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>
			<tr>
				<td>05:00 - 06:00</td>
				<td>Mencionar actividades programadas</td>
			</tr>			
		</tbody>
	</table>
</div>
<div class="inscripcion">
	<p><%= link_to "Reservar cupón",new_persona_path, :class => 'btn btn-primary'%></p>
</div>

app/views/home/_informe.html.erb
<div class="inscripcion">
	<h2>Vacantes limitadas</h2>
	<p>Te esperamos</p>
	<p><%= link_to "Reservar cupo",new_persona_path, :class => 'btn btn-primary'%></p>
	<p class="seguir">Siguenos en facebook para mayor información</p>
	<%=link_to image_tag("facebook.png", :size => "40x40"),"https://www.facebook.com/events/186894391488684/?fref=ts"%>
</div>

app/views/reportes/correos.html.erb
<div class="hero-unit">
<h1 class="text-info">Contactos con los asistentes</h1>
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>N°</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Celular</th>
      <th>Email</th>      
      <th>Región</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
	<% i=0 %>
    <% @personas.each do |persona| %>
      <tr>
		<td><%= i+=1%></td>
        <td><%= persona.nombres %></td>
        <td><%= persona.apellidos %></td>
        <td><%= persona.celular %></td>
        <td><%= persona.email %></td>
        <td><%= persona.region.nombre unless persona.region.blank? %></td>        
        
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/reportes/index.html.erb
<div class="hero-unit">
<h1 class="text-info">Asistentes al HackDay Tacna</h1>
<h4>Total de personas inscritas: <%= @totalpersona-1%></h4>
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>N°</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Celular</th>
      <th>Institución</th>
      <th>Conferencia</th>
      <th>Ocupación</th>      
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
	<% i=0 %>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= i+=1%></td>
        <td><%= persona.nombres %></td>
        <td><%= persona.apellidos %></td>
        <td><%= persona.celular %></td>
        <td><%= persona.institucion unless persona.institucion.blank?%></td>
        <td><%= persona.conferencia %></td>
        <td><%= persona.estudio.nombre %></td>        
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Cambiar roles</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Cambiar rol", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Cerrar</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="hero-unit">
<h3>Usuarios</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Usuarios</th>
      <th>Email</th>
      <th>Registrado</th>
      <th>Rol</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Cambiar rol</a>
        <%= render user %>
      </td>
      <td><%= link_to("Eliminar usuario", user_path(user), :data => { :confirm => "¿Estas seguro?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
</div>

app/views/users/show.html.erb
<h3>Usuario</h3>
<p>Usuario: <%= @user.name %></p>
<p>Correo electrónico: <%= @user.email if @user.email %></p>