config/routes.rb
HackDay::Application.routes.draw do
  
  #get "conferencias/index"
  get "conferencias/ponencias"
  get "conferencias/talleres"
  get "conferencias/costos"
  get "reportes/index"
  get "reportes/correos"  
  get "cronogramas/index"
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :personas
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/estudio.rb
class Estudio < ActiveRecord::Base
	has_many :personas
	
	validates_uniqueness_of :nombre
	validates_presence_of :nombre
end

app/models/evento.rb
class Evento < ActiveRecord::Base
	has_many :personas_eventos
	has_many :personas, :through => :personas_eventos
end

app/models/institucion.rb
class Institucion < ActiveRecord::Base
	#has_many :personas
	
	validates_uniqueness_of :nombre
	validates_presence_of :nombre
end

app/models/persona.rb
class Persona < ActiveRecord::Base
	belongs_to :region
	#belongs_to :institucion
	belongs_to :estudio
	
	has_many :personas_eventos
	has_many :eventos, :through => :personas_eventos
		
	validates :nombres, :apellidos, :email, :estudio_id, :presence => true
	
	#validates_uniqueness_of :dni
	validates_uniqueness_of :email
	#validates :dni,length: { is: 8}, :presence => true
	#validates_format_of :dni, :with => /\A[0-9]{8}\Z/
	
	validates_uniqueness_of :celular
	validates :celular,length: { is: 9}, :presence => true
	validates_format_of :celular, :with => /\A[0-9]{9}\Z/
	
	validates :comentario, length: { maximum: 150}
	
	validates :conferencia, :presence => true 
	validates :conferencia, length: { maximum: 40}
	before_validation( :on => :create) do
		predeterminados
	end	
	
	def predeterminados
		self.institucion = 'No se indico' if self.institucion.blank?		
		self.comentario = 'No comento' if self.comentario.blank?
	end
end

app/models/personas_eventos.rb
class PersonasEventos < ActiveRecord::Base
end

app/models/region.rb
class Region < ActiveRecord::Base
	has_many :personas
	
	validates_uniqueness_of :nombre
	validates_presence_of :nombre
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  # :registerable,	sirve para crear nuevos usuarios
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable,:timeoutable
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
  redirect_to root_path, :alert => exception.message
  end

end

app/controllers/conferencias_controller.rb
class ConferenciasController < ApplicationController
  def index
  end

  def ponencias
  end

  def talleres
  end

  def costos
  end
end

app/controllers/cronogramas_controller.rb
class CronogramasController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]
  before_action :set_persona, only: [:show, :edit, :update, :destroy]
  
  def edit
  end

  def new
	@persona = Persona.new
  end

  def create
	@persona = Persona.new(persona_params)
	
	if @persona.save
		flash[:notice]="Se registró correctamente"
		redirect_to root_path
	else
		render action: 'new'
	end
  end
  
  def show
  end
  
  def update
	if @persona.update(persona_params)
		flash[:notice]="Se actualizó los datos"
		redirect_to @persona
     else
        render action: 'edit'        
     end
  end
  def confirmar
  end
  def destroy
    @persona.destroy
    redirect_to reportes_index_path
  end
  private
  
  def set_persona
	@persona = Persona.find(params[:id])
  end
  
  def persona_params
	params.require(:persona).permit(:dni, :nombres, :apellidos, :email, :celular, :institucion, :region_id, :comentario, :estudio_id,:conferencia)
  end  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
	devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
  end
end

app/controllers/reportes_controller.rb
class ReportesController < ApplicationController
  before_filter :authenticate_user!
  
  def index
	@personas=Persona.all
	@totalpersona=Persona.count
  end
  
  def correos
	@personas=Persona.all.order("region_id")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/conferencias_helper.rb
module ConferenciasHelper
end

app/helpers/cronogramas_helper.rb
module CronogramasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/reportes_helper.rb
module ReportesHelper
end

app/views/personas/_confirmar.html.erb
<a href="#myModal" role="button" class="btn btn-primary" data-toggle="modal">Confirmar</a>
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
<h3 id="myModalLabel" class="text-info">Términos y condiciones</h3>
</div>
<div class="modal-body">
	<ol class="lista">
		<li>Al momento de registrarse usted se compromete a asistir al evento</li>
		<li>Usted se compromete a cuidar el ambiente que se le facilitará</li>
		<li>Cualquier falta y/o problema se aténdera al momento y se tomaran la medidas necesarias, así no encuentren estipuladas en los incisos.</li>
	</ol>
</div>
<div class="modal-footer">
<button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
<button class="btn btn-primary">Acepto</button>
</div>
</div>

app/views/personas/_form.html.erb
<%= simple_form_for(@persona) do |f| %>
  <div class="form-horizontal">
	<%= f.error_notification %>
    <%= f.input :nombres, :placeholder =>'Tus nombres completos' %>
    <%= f.input :apellidos, :placeholder =>'Tus apellidos completos' %>
    <%= f.input :email, :label => "Correo electrónico", :placeholder =>'Tu email es indespensable' %>
    <%= f.input :celular, :placeholder =>'Tu celular es indespensable' %>
    <%= f.input :institucion, :placeholder =>'Institución de procedencia'%>
    <%= f.association :region, :label =>"Departamento" ,label_method: :nombre, value_method: :id, include_blank: false, :prompt => "Seleccione tu departamento" %>
    <%= f.input :conferencia, :placeholder =>'¿Desea recibir: PONENCIA,TALLER o AMBOS?' %>    
    <%= f.input :comentario, :placeholder =>'¿Qué te motivó a participar de este evento?' %>
    <%= f.association :estudio ,label_method: :nombre, value_method: :id,:prompt => "Tu grado de estudios" %>    
  </div>
  <%= render 'confirmar'%>
  <% f.button :submit %>
<% end %>

app/views/personas/edit.html.erb
<div class="hero-unit">
<h1 class="text-info" >Editar mi información personal</h1>
<%= render 'form' %>
<%= link_to 'Atrás', root_path %>
</div>

app/views/personas/new.html.erb
<div class="hero-unit">
<h2 class="text-info">Formulario de Inscripción</h2><br>
<%= render 'form' %>
<%= link_to 'Atrás', root_path %>
</div>

app/views/personas/show.html.erb
<div class="hero-unit">
<h1 class="text-info">La información del asistente es:</h1>
<ul>
	<li>Nombres :<%= @persona.nombres %></li>
	<li>Apellidos :<%= @persona.apellidos%></li>
	<li>Correo electrónico :<%= @persona.email %></li>
	<li>Celular :<%= @persona.celular %></li>	
	<li>Institucion :<%= @persona.institucion %></li>
	<li>Región :<%= @persona.region.nombre %></li>
	<li>Estudios :<%= @persona.estudio.nombre %></li>
</ul>
<%= link_to 'Editar', edit_persona_path(@persona) %> |
<%= link_to 'Inicio', root_path %>
</div>